[tools]
selene = { source = "Kampfkarren/selene", version = "0.17.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.13.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.1.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
wally = { source = "upliftgames/wally", version = "0.3.1" }
